In [6]:
#ADS Assignment1            VISWA BRAHMANA NANDA KISHORE              20BEC0260

In [2]:
#Q1
name="Nanda Kishore"
age=21
print("Name: ",name)
print("Age: ",age)


Name:  Nanda Kishore
Age:  21


In [6]:
#User input
n=input("Enter the name: ")
a=input("ENter Age: ")
print("My Name is ",n," and I am ",a," years old.")

Enter the name:  Nanda Kishore
ENter Age:  21


My Name is  Nanda Kishore  and I am  21  years old.


In [3]:
#Q2
X="Datascience is used to derive meaningful insights"
y=X.split()
print(y)

['Datascience', 'is', 'used', 'to', 'derive', 'meaningful', 'insights']


In [3]:
#Q3
def mul(a,b):
    c=a*b
    print(c)
mul(2,3)

6


In [5]:
#Q4
dict = {"Andhra Pradesh":"Amaravathi","Karnataka":"Banglore","Tamil Nadu":"CHennai","Maharashtra":"Mumbai","Kerala":"Tiruvanantapuram"}
x=dict.keys()
y=dict.values()
print( x," \n",y)

dict_keys(['Andhra Pradesh', 'Karnataka', 'Tamil Nadu', 'Maharashtra', 'Kerala'])  
 dict_values(['Amaravathi', 'Banglore', 'CHennai', 'Mumbai', 'Tiruvanantapuram'])


In [16]:
#Q5
a=list(range(1,1001))
print(a)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [17]:
#Q6
import numpy as np
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#Q7
arr=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(arr)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [21]:
#Q8
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[9,8,7],[6,5,4],[3,2,1]])
sum = arr1+arr2
print(sum)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [2]:
#Q9
import pandas as pd
dates = pd.date_range('2023-02-01', '2023-03-01')
print(dates)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


In [24]:
#Q10
import pandas as pd
dict = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
a = pd.DataFrame(dict)
print(a)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
